
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugwpnonuqhwjagwdpnbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnd3Bub251cWh3amFnd2RwbmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODU1MjcsImV4cCI6MjA2NTY2MTUyN30.vIiLxU3TG0teOZIzA1k1E9NrSTKE5G1kDqoxqDC76Xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'Content-Type': 'application/json'
    },
    fetch: (url, options = {}) => {
      console.log('Supabase fetch:', url);
      return fetch(url, {
        ...options,
        signal: AbortSignal.timeout(10000), // 10 segundo timeout
      }).catch(error => {
        console.error('Supabase fetch error:', error);
        throw error;
      });
    }
  },
  db: {
    schema: 'public'
  }
});

// Log de inicialização
console.log('Supabase client inicializado com:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY
});
